# NameError exception

In python, when a global or local variable is not find, the `NameError` exception is raised. 

``` python
In [94]: asdf()  
---------------------------------------------------------------------------  
NameError                                 Traceback (most recent call last)  
<ipython-input-94-e0895bb989ae> in <module>  
----> 1 asdf()  
  
NameError: name 'asdf' is not defined
```
#Python 